steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA", "."]
    timeout: 500s

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"]

  # Deploy container image to Cloud Run
  # Service name must use only lowercase alphanumeric characters and dashes. Cannot begin or end with a dash, and cannot be longer than 63 characters.
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "$REPO_NAME",
        "--image",
        "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA",
        "--region",
        "asia-northeast1",
        "--platform",
        "managed",
      ]
images:
  - "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"
